/**
 *
 * @author SEAMAC
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.jdbc.JDBCCategoryDataset;




public class Hauptoberflaeche extends javax.swing.JFrame {


    public void ChartJFrame_erzeugen(ChartPanel cp, String Titel, int preferred_width, int preferred_height) {
        JFrame myWindow = new JFrame(Titel);
        JPanel panel = new JPanel();
        //myWindow.setPreferredSize(new Dimension(preferred_width, preferred_height));

        //myWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        myWindow.setTitle(Titel);
        myWindow.setSize(preferred_width, preferred_height); // Reihenfolge zw. setLocation und setSize ist wichtig! Sonst wird JFrame erst ab Displaymitte vergr��ert
        myWindow.setLocationRelativeTo(null);
        //myWindow.setLayout(new BorderLayout());
        myWindow.setResizable(true);

        // myWindow.setExtendedState(myWindow.MAXIMIZED_BOTH); // (Fast) Fullscreen
        myWindow.setUndecorated(false);

        panel.add(cp);
        myWindow.setLayout(new FlowLayout());
        myWindow.add(panel);
        myWindow.validate();
        myWindow.pack();

        myWindow.setVisible(true);

    }


    private ChartPanel chartPanel_erzeugen(String Tabelle) {
        try {
            String query = "SELECT * FROM phpmyadmin." + Tabelle + ";";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(mySQLverbindung, query);
            JFreeChart chart = ChartFactory.createLineChart((String) Tabelle, "Zeitstempel", "Temperaturen in C", dataset, PlotOrientation.VERTICAL, true, true, true);
            CategoryAxis axis = chart.getCategoryPlot().getDomainAxis();
            chart.setBackgroundPaint(null);//damit hintergrund des Charts transparent ist --> PNGs etc. werden auch transparenten background haben
            axis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
            chartPanel_tempueberw = new ChartPanel(chart);//createChart((String)Tabelle, "Zeitstempel","Temperaturen in C",dataset));
            return chartPanel_tempueberw;
        } catch (SQLException ex) {
            Logger.getLogger(Hauptoberflaeche.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Es konnte kein chartPanel erzeugt werden:\n" + ex);
            return null;
        }
    }



    public Hauptoberflaeche() {
        if (mySQLverbindung != null) {

            //Damit alle JTables farblich alternierende Zeilen haben
            UIDefaults defaults = UIManager.getLookAndFeelDefaults();
            if (defaults.get("Table.alternateRowColor") == null) {
                defaults.put("Table.alternateRowColor", new Color(200, 200, 200)); // RGB-Code entspricht 'Grau'. Je höher desto heller.
            }
            // Das Fenster initialisieren etc.
            initComponents();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Produktionsverw_Tab = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        Lieferanten = new javax.swing.JPanel();
        Roh_Hilfsstoffe_Tab = new javax.swing.JPanel();
        Chargenverfolgung = new javax.swing.JPanel();
        Lagerverwalt_Tab = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Bestand_Tab = new javax.swing.JPanel();
        Sorten_Artikel_Tab = new javax.swing.JPanel();
        Kunden_Tab = new javax.swing.JPanel();
        Bestellungen_Tab = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        Offene_Best_Tab = new javax.swing.JPanel();
        Erledigte_Best_Tab = new javax.swing.JPanel();
        Lieferungen_Tab = new javax.swing.JPanel();
        Wareneingaenge_Tab = new javax.swing.JPanel();
        Warenausgaenge_Tab = new javax.swing.JPanel();
        Personalverw_Tab = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        Mitarbeiter_Tab = new javax.swing.JPanel();
        Zeiterfassung_Tab = new javax.swing.JPanel();
        Temperaturueb_Tab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox_Tempuberw = new javax.swing.JComboBox();
        TemperaturChart_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DokumentationUndDatein_Tab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARSLAN KEBAP Verwaltung 0.1b");
        setModalExclusionType(null);
        setName("Haupt_JFrame"); // NOI18N

        jTabbedPane1.setAutoscrolls(true);

        javax.swing.GroupLayout LieferantenLayout = new javax.swing.GroupLayout(Lieferanten);
        Lieferanten.setLayout(LieferantenLayout);
        LieferantenLayout.setHorizontalGroup(
            LieferantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        LieferantenLayout.setVerticalGroup(
            LieferantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Lieferanten", Lieferanten);

        javax.swing.GroupLayout Roh_Hilfsstoffe_TabLayout = new javax.swing.GroupLayout(Roh_Hilfsstoffe_Tab);
        Roh_Hilfsstoffe_Tab.setLayout(Roh_Hilfsstoffe_TabLayout);
        Roh_Hilfsstoffe_TabLayout.setHorizontalGroup(
            Roh_Hilfsstoffe_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Roh_Hilfsstoffe_TabLayout.setVerticalGroup(
            Roh_Hilfsstoffe_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Roh-Hilfsstoffe", Roh_Hilfsstoffe_Tab);

        javax.swing.GroupLayout ChargenverfolgungLayout = new javax.swing.GroupLayout(Chargenverfolgung);
        Chargenverfolgung.setLayout(ChargenverfolgungLayout);
        ChargenverfolgungLayout.setHorizontalGroup(
            ChargenverfolgungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        ChargenverfolgungLayout.setVerticalGroup(
            ChargenverfolgungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Chargenverfolgung", Chargenverfolgung);

        javax.swing.GroupLayout Produktionsverw_TabLayout = new javax.swing.GroupLayout(Produktionsverw_Tab);
        Produktionsverw_Tab.setLayout(Produktionsverw_TabLayout);
        Produktionsverw_TabLayout.setHorizontalGroup(
            Produktionsverw_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        Produktionsverw_TabLayout.setVerticalGroup(
            Produktionsverw_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane1.addTab("Produktionsverwaltung", Produktionsverw_Tab);

        jTabbedPane2.setMinimumSize(new java.awt.Dimension(1200, 172));

        javax.swing.GroupLayout Bestand_TabLayout = new javax.swing.GroupLayout(Bestand_Tab);
        Bestand_Tab.setLayout(Bestand_TabLayout);
        Bestand_TabLayout.setHorizontalGroup(
            Bestand_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
        );
        Bestand_TabLayout.setVerticalGroup(
            Bestand_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Bestand", Bestand_Tab);

        javax.swing.GroupLayout Sorten_Artikel_TabLayout = new javax.swing.GroupLayout(Sorten_Artikel_Tab);
        Sorten_Artikel_Tab.setLayout(Sorten_Artikel_TabLayout);
        Sorten_Artikel_TabLayout.setHorizontalGroup(
            Sorten_Artikel_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
        );
        Sorten_Artikel_TabLayout.setVerticalGroup(
            Sorten_Artikel_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Sorten/Artikel", Sorten_Artikel_Tab);

        javax.swing.GroupLayout Kunden_TabLayout = new javax.swing.GroupLayout(Kunden_Tab);
        Kunden_Tab.setLayout(Kunden_TabLayout);
        Kunden_TabLayout.setHorizontalGroup(
            Kunden_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
        );
        Kunden_TabLayout.setVerticalGroup(
            Kunden_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Kunden", Kunden_Tab);

        jTabbedPane3.setPreferredSize(new java.awt.Dimension(1135, 700));

        Offene_Best_Tab.setPreferredSize(new java.awt.Dimension(1114, 700));

        javax.swing.GroupLayout Offene_Best_TabLayout = new javax.swing.GroupLayout(Offene_Best_Tab);
        Offene_Best_Tab.setLayout(Offene_Best_TabLayout);
        Offene_Best_TabLayout.setHorizontalGroup(
            Offene_Best_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        Offene_Best_TabLayout.setVerticalGroup(
            Offene_Best_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Offene", Offene_Best_Tab);

        Erledigte_Best_Tab.setPreferredSize(new java.awt.Dimension(1114, 700));

        javax.swing.GroupLayout Erledigte_Best_TabLayout = new javax.swing.GroupLayout(Erledigte_Best_Tab);
        Erledigte_Best_Tab.setLayout(Erledigte_Best_TabLayout);
        Erledigte_Best_TabLayout.setHorizontalGroup(
            Erledigte_Best_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        Erledigte_Best_TabLayout.setVerticalGroup(
            Erledigte_Best_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Erledigte", Erledigte_Best_Tab);

        javax.swing.GroupLayout Bestellungen_TabLayout = new javax.swing.GroupLayout(Bestellungen_Tab);
        Bestellungen_Tab.setLayout(Bestellungen_TabLayout);
        Bestellungen_TabLayout.setHorizontalGroup(
            Bestellungen_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
            .addGroup(Bestellungen_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1179, Short.MAX_VALUE))
        );
        Bestellungen_TabLayout.setVerticalGroup(
            Bestellungen_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
            .addGroup(Bestellungen_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Bestellungen", Bestellungen_Tab);

        javax.swing.GroupLayout Lieferungen_TabLayout = new javax.swing.GroupLayout(Lieferungen_Tab);
        Lieferungen_Tab.setLayout(Lieferungen_TabLayout);
        Lieferungen_TabLayout.setHorizontalGroup(
            Lieferungen_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
        );
        Lieferungen_TabLayout.setVerticalGroup(
            Lieferungen_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Lieferungen", Lieferungen_Tab);

        javax.swing.GroupLayout Wareneingaenge_TabLayout = new javax.swing.GroupLayout(Wareneingaenge_Tab);
        Wareneingaenge_Tab.setLayout(Wareneingaenge_TabLayout);
        Wareneingaenge_TabLayout.setHorizontalGroup(
            Wareneingaenge_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
        );
        Wareneingaenge_TabLayout.setVerticalGroup(
            Wareneingaenge_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Wareneingaenge", Wareneingaenge_Tab);

        javax.swing.GroupLayout Warenausgaenge_TabLayout = new javax.swing.GroupLayout(Warenausgaenge_Tab);
        Warenausgaenge_Tab.setLayout(Warenausgaenge_TabLayout);
        Warenausgaenge_TabLayout.setHorizontalGroup(
            Warenausgaenge_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
        );
        Warenausgaenge_TabLayout.setVerticalGroup(
            Warenausgaenge_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Warenausgaenge", Warenausgaenge_Tab);

        javax.swing.GroupLayout Lagerverwalt_TabLayout = new javax.swing.GroupLayout(Lagerverwalt_Tab);
        Lagerverwalt_Tab.setLayout(Lagerverwalt_TabLayout);
        Lagerverwalt_TabLayout.setHorizontalGroup(
            Lagerverwalt_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Lagerverwalt_TabLayout.setVerticalGroup(
            Lagerverwalt_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lagerverwaltung", Lagerverwalt_Tab);

        javax.swing.GroupLayout Mitarbeiter_TabLayout = new javax.swing.GroupLayout(Mitarbeiter_Tab);
        Mitarbeiter_Tab.setLayout(Mitarbeiter_TabLayout);
        Mitarbeiter_TabLayout.setHorizontalGroup(
            Mitarbeiter_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        Mitarbeiter_TabLayout.setVerticalGroup(
            Mitarbeiter_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Mitarbeiter", Mitarbeiter_Tab);

        javax.swing.GroupLayout Zeiterfassung_TabLayout = new javax.swing.GroupLayout(Zeiterfassung_Tab);
        Zeiterfassung_Tab.setLayout(Zeiterfassung_TabLayout);
        Zeiterfassung_TabLayout.setHorizontalGroup(
            Zeiterfassung_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        Zeiterfassung_TabLayout.setVerticalGroup(
            Zeiterfassung_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Zeiterfassung", Zeiterfassung_Tab);

        javax.swing.GroupLayout Personalverw_TabLayout = new javax.swing.GroupLayout(Personalverw_Tab);
        Personalverw_Tab.setLayout(Personalverw_TabLayout);
        Personalverw_TabLayout.setHorizontalGroup(
            Personalverw_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        Personalverw_TabLayout.setVerticalGroup(
            Personalverw_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        jTabbedPane1.addTab("Personalverwaltung", Personalverw_Tab);

        Temperaturueb_Tab.setLayout(new java.awt.BorderLayout());
        Temperaturueb_Tab.setLayout(new java.awt.BorderLayout());

        jComboBox_Tempuberw.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TempRaum1", "TempRaum2", "Item 3", "Item 4" }));
        jComboBox_Tempuberw.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                // Get the source of the component, which is our combobox:
                try{
                    comboBox1_bei_Tempueberw = (JComboBox) event.getSource();
                    Object selected = comboBox1_bei_Tempueberw.getSelectedItem();
                    // In einer der Temperaturueberwachungstabellen ausgewaehle DB anzeigen:
                    TabellenOperationen.JTableJFrame_erzeugen((String)selected, "SELECT * FROM phpmyadmin." + (String)selected + ";", 800,800);
                    // Gleichzeitig den dazugehörigen Graph anzeigen, hierfür stets Komponente im Center des Panels entfernen und ChartPanel neu zum Center hinzufuegen:
                    BorderLayout layout = (BorderLayout) Temperaturueb_Tab.getLayout();
                    if (layout.getLayoutComponent(BorderLayout.CENTER) != null) {
                        Temperaturueb_Tab.remove(layout.getLayoutComponent(BorderLayout.CENTER));
                    }

                    //ChartJFrame_erzeugen(cp, (String)selected, 500, 500);
                    Temperaturueb_Tab.add(chartPanel_erzeugen((String)selected));//, BorderLayout.CENTER);
                Temperaturueb_Tab.validate();

            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    });
    jComboBox_Tempuberw.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox_TempuberwActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jComboBox_Tempuberw, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 954, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jComboBox_Tempuberw, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    Temperaturueb_Tab.add(jPanel1, java.awt.BorderLayout.PAGE_END);

    TemperaturChart_Panel.setBackground(new java.awt.Color(0, 0, 0));
    TemperaturChart_Panel.setToolTipText("");
    TemperaturChart_Panel.setLayout(new java.awt.BorderLayout());
    Temperaturueb_Tab.add(TemperaturChart_Panel, java.awt.BorderLayout.CENTER);
    Temperaturueb_Tab.add(chartPanel_erzeugen("TempRaum1"));//, BorderLayout.CENTER);
    Temperaturueb_Tab.validate();

    jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 153, 255));
    jLabel2.setText(" TEMPERATURUEBERWACHUNG");
    Temperaturueb_Tab.add(jLabel2, java.awt.BorderLayout.PAGE_START);

    jTabbedPane1.addTab("Temperaturueberwachung", Temperaturueb_Tab);

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 153, 0));
    jLabel1.setText(" DOKUMENTENVERWALTUNG");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 889, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 472, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout DokumentationUndDatein_TabLayout = new javax.swing.GroupLayout(DokumentationUndDatein_Tab);
    DokumentationUndDatein_Tab.setLayout(DokumentationUndDatein_TabLayout);
    DokumentationUndDatein_TabLayout.setHorizontalGroup(
        DokumentationUndDatein_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(DokumentationUndDatein_TabLayout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(DokumentationUndDatein_TabLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(284, Short.MAX_VALUE))
    );
    DokumentationUndDatein_TabLayout.setVerticalGroup(
        DokumentationUndDatein_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(DokumentationUndDatein_TabLayout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(33, 33, 33)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(106, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dokumentation und Datein", DokumentationUndDatein_Tab);

    jMenu1.setText("Gehe zu...");

    jMenuItem1.setText("Test");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem1ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem1);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Y");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Z");
    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }//GEN-END:initComponents

    private void jComboBox_TempuberwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TempuberwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TempuberwActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Hauptoberflaeche().setVisible(true);
            }
        });
    }

    // Manuelle Variablendeklaration (da Gui-Designer grenzen hat):
    static Connection mySQLverbindung = mySQLVerbindungAufbauen.mySQLVerbindungAufbauen();
    PreparedStatement mySQL_prepared_statement = null;
    ResultSet mySQLresultset = null;
    JComboBox comboBox1_bei_Tempueberw;
    ChartPanel chartPanel_tempueberw = null;
    JFrame myWindow = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bestand_Tab;
    private javax.swing.JPanel Bestellungen_Tab;
    private javax.swing.JPanel Chargenverfolgung;
    private javax.swing.JPanel DokumentationUndDatein_Tab;
    private javax.swing.JPanel Erledigte_Best_Tab;
    private javax.swing.JPanel Kunden_Tab;
    private javax.swing.JPanel Lagerverwalt_Tab;
    private javax.swing.JPanel Lieferanten;
    private javax.swing.JPanel Lieferungen_Tab;
    private javax.swing.JPanel Mitarbeiter_Tab;
    private javax.swing.JPanel Offene_Best_Tab;
    private javax.swing.JPanel Personalverw_Tab;
    private javax.swing.JPanel Produktionsverw_Tab;
    private javax.swing.JPanel Roh_Hilfsstoffe_Tab;
    private javax.swing.JPanel Sorten_Artikel_Tab;
    private javax.swing.JPanel TemperaturChart_Panel;
    private javax.swing.JPanel Temperaturueb_Tab;
    private javax.swing.JPanel Warenausgaenge_Tab;
    private javax.swing.JPanel Wareneingaenge_Tab;
    private javax.swing.JPanel Zeiterfassung_Tab;
    public javax.swing.JComboBox jComboBox_Tempuberw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables



}
